on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    env:
      MV_DEVICE_SID: 'UVxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      TWILIO_ACCOUNT_SID: 'ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      TWILIO_AUTH_TOKEN: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build docker image
      run: docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t microvisor-gpio-sample-image .
    - name: Build code
      run: docker run --rm -v $(pwd)/:/home/mvisor/project/ --env-file env.list --name microvisor-gpio-sample microvisor-gpio-sample-image
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gpio_toggle_demo
        path: ${{ github.workspace }}/build/Demo/gpio_toggle_demo.*
