on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:


    # when submodule is public, this can be used:
    #- name: Check out code
      #uses: actions/checkout@v2
      #with:
        #submodules: true


    # while submodule is private, we need to force checkout@v2 to use our key :|
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: false
    - name: Create ssh key
      run: |
        mkdir -p ~/.ssh
        cat << EOF > ~/.ssh/submodulekey
        ${{ secrets.HAL_SUBMODULE_PULL_KEY }}
        EOF
        chmod 700 ~/.ssh/submodulekey
    - name: create ssh-config
      run: |
        cat << EOF > ~/.ssh/config
        Host github.com-twilio
        HostName github.com
        User git
        IdentityFile ~/.ssh/submodulekey
        EOF
    - name: force gitmodules to use key
      run: |
        sed -i 's/@github.com:twilio/@github.com-twilio:twilio/g' .gitmodules
    - name: fetch submodules manually
      run: |
        git submodule sync
        git submodule update --init --recursive
    - name: cleanup key
      run: |
        rm ~/.ssh/submodulekey


    - name: Build docker image
      run: docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t microvisor-gpio-sample-image .
    - name: Build code
      run: docker run --rm -v $(pwd)/:/home/ --name microvisor-gpio-sample microvisor-gpio-sample-image
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gpio_toggle_demo
        path: ${{ github.workspace }}/build/gpio_toggle_demo.*
